<<<<<<< 4bfa93fd6705874416f16ac5d9d2dbfb2df07cae
// THIS FILE IS GENERATED BY SCRIPT, DO NOT EDIT!!
#include <stdint.h>
#define fstr ""

//#define FONT_GETSIZE(w,h) (w*h>>1)
=======
#include <stdint.h>
#define fstr ""

#define FONT_GETSIZE(w,h) (w*h>>1)
>>>>>>> 1st commit

/*0*/
extern const uint16_t res_string_0[];
/*1*/
extern const uint16_t res_string_1[];
/*2*/
extern const uint16_t res_string_2[];
/*3*/
extern const uint16_t res_string_3[];
/*4*/
extern const uint16_t res_string_4[];
/*5*/
extern const uint16_t res_string_5[];
/*6*/
extern const uint16_t res_string_6[];
/*7*/
extern const uint16_t res_string_7[];
/*8*/
extern const uint16_t res_string_8[];
/*9*/
extern const uint16_t res_string_9[];
<<<<<<< 4bfa93fd6705874416f16ac5d9d2dbfb2df07cae
/*对于在快速处理器上使用的较慢显示控制器,使用端口线可能是唯一的解决方案。这种访问显示器的方法有一个缺点,比直接总线接口稍微慢些,但是缓存能最小化对显示器的访问,因此显示更新不会显著减慢。所有需要做的事情就是定义例程或宏,设置或读取显示器。*/
extern const uint16_t res_string_10[];
/*10*/
extern const uint16_t res_string_11[];
/*11*/
extern const uint16_t res_string_12[];
/*12*/
extern const uint16_t res_string_13[];
/*:*/
extern const uint16_t res_string_14[];
/* */
extern const uint16_t res_string_15[];
extern const uint32_t res_glyph_index[];
=======
/*10*/
extern const uint16_t res_string_10[];
/*11*/
extern const uint16_t res_string_11[];
/*12*/
extern const uint16_t res_string_12[];
/*:*/
extern const uint16_t res_string_13[];
/* */
extern const uint16_t res_string_14[];
extern const uint16_t res_glyph_index[];
>>>>>>> 1st commit
extern const uint8_t res_glyphs[];
extern const uint16_t res_img_res_lp_jpg[];
